"""added category model

Revision ID: 576ecce2decd
Revises: ffdc0a98111c
Create Date: 2022-01-19 15:53:47.508191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '576ecce2decd'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    # ### end Alembic commands ###
